# Generated by Django 3.2.11 on 2022-12-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
